name:                almorin
version:             0.1.0.0
github:              "saskali/almorin"
homepage:            https://github.com/saskali/almorin
license:             BSD3
author:              "Saskia Lindner"
copyright:           "2019 Saskia Lindner"

extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - tidal

executables:
  almorin:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tidal
